honssa/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include('admin.urls')),
    path('user/', include('user.urls')),
    path('honssa/', include('honssauser.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

honssa/user/urls.py
from django.urls import path
from .views import *

app_name = "user"

urlpatterns = [
    path("login/",login_view, name="login"),
    path("logout/",logout_view , name="logout"),
    path("signup/",signup_view, name="signup"),
    path("find_id/",find_id, name="find_id"),
    path("find_password/",find_password, name="find_password")
]

honssa/user/models.py
from django.db import models
from django.urls import reverse
from admin.models import *

# Create your models here.

honssa/user/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import auth
from admin.models import *

# Create your views here.

def login_view(request):
    if request.method == "POST":
        print(request.POST)
        username = request.POST["username"]
        password = request.POST["password"]
        user = auth.authenticate(request, username=username, password=password)
        print(username, password)
        if user is not None:
            print("인증")
            login(request, user)
            return redirect('honssauser:main')
        else:
            print("실패")
            return redirect('user:login')

    return render(request,  "user/login.html")

def logout_view(request):
    logout(request)
    return redirect("user:login")

def signup_view(request):

    if request.method == 'POST':
        # if member_tbl.object.filter(member_id = user_id).exists:
        #     print('중복아님')
            if request.POST['password'] == request.POST['password2']:
                print(request.POST)
                username = request.POST['username']
                useremail = request.POST['useremail']
                user_id = request.POST['user_id']
                password = request.POST['password']
                hpon = request.POST['hpon']

                print(request.POST)
                New_data = member_tbl(
                    member_name = username,
                    member_email = useremail,
                    member_id = user_id,
                    member_password = password,
                    member_contact_number = hpon,
                )
                users = User.objects.create_user(user_id, useremail, password)
                users.last_name = 'x'
                users.first_name = 'x'
                users.save()
                New_data.save()
                return redirect("user:login")
                # return render("user:login")
            else:
                print('패스워드 틀림')
        # else:
        #     print('중복')
    return render(request, "user/signup.html")

def find_id(request):
    member = []
    msg = ''
    if request.method == 'POST':
        member = member_tbl.objects.filter(member_name=request.POST['username'], member_email=request.POST['useremail'])
        if member:
            member = member[0]
        else:
            msg = '이름 혹은 이메일이 일치하지 않습니다.'
    print(request.POST)
    content = {'member': member, 'msg': msg}
    return render(request, 'user/find_id.html', content)

def find_password(request):
    member = []
    msg = ''
    if request.method == 'POST':
        member = member_tbl.objects.filter(member_id = request.POST['username'], member_email=request.POST['useremail'])
        if member:
            member = member[0]
        else:
            msg = '아이디 혹은 이메일이 일치하지 않습니다.'
    content = {'member': member, 'msg': msg}
    return render(request, 'user/find_password.html', content)

honssa/templates/user/detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Ecommerce">
    <title>eMart - eCommerce Website Template</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="assets/img/honssamain.png">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="assets/css/bootstrap.min.css" type="text/css">
    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="assets/fonts/font-awesome.min.css" type="text/css">
    <!-- Line Icons CSS -->
    <link rel="stylesheet" href="assets/fonts/line-icons/line-icons.css" type="text/css">
    <!-- Main Styles -->
    <link rel="stylesheet" href="assets/css/main.css" type="text/css">

    <!-- Animate CSS -->
    <link rel="stylesheet" href="assets/extras/animate.css" type="text/css">
    <!-- Owl Carousel -->
    <link rel="stylesheet" href="assets/extras/owl.carousel.css" type="text/css">
    <link rel="stylesheet" href="assets/extras/owl.theme.css" type="text/css">
    <!-- Slicknav Css -->
    <link rel="stylesheet" href="assets/css/slicknav.css" type="text/css">
    <!-- Responsive CSS Styles -->
    <link rel="stylesheet" href="assets/css/responsive.css" type="text/css">
    <link rel="stylesheet" href="assets/css/as.css" type="text/css">
  </head>

  <body>
    <!-- Header Section Start -->
    <div class="header">

      <!-- Start Top Bar -->
      <div class="top-bar">
        <div class="container">
          <div class="row">
            <div class="col-md-4 col-sm-2">
              <div class="language-wrapper">
                <div class="box-language">
                  <form id="form-language">
                    <div class="btn-group toggle-wrap">
                    </div>
                  </form>
                </div>
                <a href="#"><i class="icon-phone"></i> honssa Call: (123) 456- 789</a>
              </div>
              <div class="clear"></div>
            </div>
            <div class="col-md-8 col-sm-10">
              <!-- shopping cart end -->
              <div class="search-area">
                <form>
                  <div class="control-group">
                    <ul class="categories-filter animate-dropdown">
                      <li class="dropdown"> <a class="dropdown-toggle" data-toggle="dropdown" href="#">카테고리 <span class="caret"></span></a>
                        <ul class="dropdown-menu animated fadeIn">
                          <li class="menu-header">종류</li>
                          <li><a tabindex="-1" href="#">- 제품1</a></li>
                          <li><a tabindex="-1" href="#">- 제품2</a></li>
                          <li><a tabindex="-1" href="#">- 제품3</a></li>
                        </ul>
                      </li>
                    </ul>
                    <input class="search-field" placeholder="Search here...">
                    <a class="search-button" href="#"><i class="icon-magnifier"></i></a>
                  </div>
                </form>
              </div>
              <div class="shop-cart">
                <ul>
                  <li><a class="cart-icon cart-btn" href="wishlist.html"><span class="icon-heart"></span></a></li>
                  <li>
                    <a href="cart.html" class="cart-icon cart-btn"><i class="icon-basket"></i></span></a>
                        </div>
                        <div class="account link-inline">
                          <a href="#"><i class="icon-login"></i><span class="hidden-mobile">로그아웃</span></a>
                        </div>
                      </div>
                    </div>
                  </li>
                </ul>
              </div>

            </div>
          </div>
        </div>
      </div>
      <!-- End Top Bar -->
    <!-- Start  Logo & Naviagtion  -->
      <nav class="navbar navbar-default" data-spy="affix" data-offset-top="50">
        <div class="container">
          <div class="row">
            <div class="navbar-header">
              <!-- Stat Toggle Nav Link For Mobiles -->
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <i class="fa fa-bars"></i>
              </button>
              <a class="navbar-brand" href="mainpage.html">
                <div><img src="assets/img/honssamain.png" alt ="" height="50px"> </div>
              </a>
            </div>
            <div class="navbar-collapse collapse">
              <!-- Start Navigation List -->
              <ul class="nav navbar-nav navbar-right">
                <li>
                  <a class="active" href="mainpage.html">메인페이지</a>

                </li>
                <li>
                  <a href="#">카테고리 <span class="caret"></span></a>
                  <div class="dropdown">
                    <div class="row">
                      <div class="ccol-sm-6 col-xs-12">
                        <ul class="menulinks">
                          <li class="maga-menu-title">
                            <a href="#">카테고리</a>
                          </li>
                          <li>
                              <a href="category.html">예시</a>
                         </li>
                        </ul>
                      </div>
                      <div class="col-sm-3 col-xs-12">
                      </div>
                      <div class="col-sm-5 col-sm-offset-1 col-xs-12">
                        <span class="block-last">
                        </span>
                      </div>
                    </div>
                  </div>
                </li>
                <li>
                  <a href="#">고객센터 <span class="caret"></span></a>
                  <div class="dropdown">
                    <div class="row">
                      <div class="ccol-sm-6 col-xs-12">
                        <ul class="menulinks">
                          <li class="maga-menu-title">
                            <a href="#">카테고리</a>
                          </li>
                          <li>
                              <a href="category.html">예시</a>
                         </li>
                        </ul>
                      </div>
                      <div class="col-sm-3 col-xs-12">
                      </div>
                      <div class="col-sm-5 col-sm-offset-1 col-xs-12">
                        <span class="block-last">
                        </span>
                      </div>
                    </div>
                  </div>
                </li>
                <li>
                  <a href="#">마이페이지 <span class="caret"></span></a>
                  <div class="dropdown">
                    <div class="row">
                      <div class="ccol-sm-6 col-xs-12">
                        <ul class="menulinks">
                          <li class="maga-menu-title">
                            <a href="#">카테고리</a>
                          </li>
                          <li>
                              <a href="category.html">예시</a>
                         </li>
                        </ul>
                      </div>
                      <div class="col-sm-3 col-xs-12">
                      </div>
                      <div class="col-sm-5 col-sm-offset-1 col-xs-12">
                        <span class="block-last">
                        </span>
                      </div>
                    </div>
                  </div>
                </li>
                <li>
                  <a href="about.html">예</a>
                </li>
              </ul>
              <!-- End Navigation List -->
            </div>
          </div>
        </div>
      </div>
        <!-- End Header Logo & Naviagtion -->
      </nav>
    </div>
    <!-- Header Section End -->
    <!-- Shop Collection Section Start -->
    <div class = product_view>
        <h2> 제품 이름</h2>
        <table>
            <caption>
                <details>
                    <summary>상품 정보</summary>
                    판매가, 상품코드 , 옵션 및 결제금액 안내
                </details>
            </caption>
            <colgroup>
            <col style="widows: 173px;">
            <col>
            </colgroup>
            <tbody>
            <tr>
                <th>판매가</th>
                <td class="price">129,000</td>
            </tr>
            <tr>
                <th>상품코드</th>
                <td>c004843</td>
            </tr>
            <tr>
                <th>국내산</th>
                <td>국내산</td>
            </tr>
            <tr>
                <th>구매수량</th>
                <td>
                    <div calss = length>
                        <input type="number" min ="1" >
                        <a href="#a"증가></a>
                        <a href="#a"감소></a>
                    </div>
                </tr>
            <tr>
                <th>옵션선택</th>
                <td>
                    <select>
                    <option>기본(+0)</option>
                    </select>
                </td>
            </tr>
            <tr>
                <th>결제금액</th>
                <td class="total"><b>129,000</b>원</td>
            </tr>
            </tbody>
        </table>
        <div class = "img">
            <img src = "assets/img/헤어드라이.png" alt = "">
        </div>
        <div class = btns>
            <a href="#">장바구니</a>
            <a href="#">구매하기</a>
        </div>


    </div><br>
    <div class="defailimg">
        <h4> 제품 상세 설명</h4>
        <img src = "assets/img/헤어드라이어_상세표시.JPG" alt="">
    </div>  <br>
     <!-- Footer Start -->
    <footer>
      <div id="copyright">
        <div class="container">
          <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
              <p>(주) 혼싸(Honssa) | 대표 000 | 사업자등록번호 xxx-xx-xxxxxxx
                문의 전화 xx-xxx-xxxx(xxxx) 영업시간 AM 10:00 ~ PM 7:00
                주소 (매장, 사무실) | 문의 메일 honssa@naver.com
                </p>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <!-- Footer End -->
    <!-- Go To Top Link -->
    <a href="#" class="back-to-top">
      <i class="icon-arrow-up"></i>
    </a>


    <!-- Start Loader -->
    <div id="loader">
      <div class="sk-folding-cube">
        <div class="sk-cube1 sk-cube"></div>
        <div class="sk-cube2 sk-cube"></div>
        <div class="sk-cube4 sk-cube"></div>
        <div class="sk-cube3 sk-cube"></div>
      </div>
    </div>

    <!-- All js here -->
    <script type="text/javascript" src="assets/js/jquery-min.js"></script>
    <script type="text/javascript" src="assets/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="assets/js/owl.carousel.min.js"></script>
    <script type="text/javascript" src="assets/js/classie.js"></script>
    <script type="text/javascript" src="assets/js/slick.min.js"></script>
    <script type="text/javascript" src="assets/js/jquery.slicknav.js"></script>
    <script type="text/javascript" src="assets/js/main.js"></script>

  </body>
</html>

honssa/templates/user/find_id.html
{% load static %}

<html lang="ko">
    <head>
        <meta charset="UTF-8">
        <title>회원가입</title>
        <link rel="stylesheet" href="{% static 'css/login.css' %}" type="text/css">
    </head>
    <body class="login" style="background-image: url({% static 'assets/img/honssamain.png' %});">
        <div class="login">
            <form action ="" method = "POST">
                {% csrf_token %}
                <p>
                    <label for="name">이름</label><br>
                    <input id = "name" type="text" name="username" value="{{ member.member_name }}">
                </p>
                <p> <label for="email">이 메 일:</label><br>
                    <input id = "email" type="email"  name="useremail" value="{{ member.member_email }}">
                </p>
                <p> <label for="password">아이디:</label><br>
                    <input id="password" type="text" style="cursor: context-menu; color: red;" name="password" value="{{ member.member_id }}" readonly>
                </p>
                {% if member %}
                <input type="button" onclick="location.href='../find_password/'" style="width: 100px;margin: 0px 2px;margin-left: -5px;" value="비밀번호찾기">
                {% else %}
                <input type ="submit" style="width: 80px;margin: 0px 2px;" value="찾기">
                {% endif %}
                <a href = "../login/"><input type="button" style="width: 80px;margin: 0px 2px;" value="뒤로가기"></a>
            </form>
        </div>
    </body>
    <script>
        {% if msg %}
            alert('{{ msg }}');
        {% endif %}
    </script>
</html>

honssa/templates/user/find_password.html
{% load static %}

<html lang="ko">
    <head>
        <meta charset="UTF-8">
        <title>회원가입</title>
        <link rel="stylesheet" href="{% static 'css/login.css' %}" type="text/css">
    </head>
    <body class="login" style="background-image: url({% static 'assets/img/honssamain.png' %});">
        <div class="login">
            <form action ="" method = "POST">
                {% csrf_token %}
                <p>
                    <label for="name">아 이 디:</label><br>
                    <input id = "name" type="text" name="username" value="{{ member.member_id }}">
                </p>
                <p> <label for="email">이 메 일:</label><br>
                    <input id = "email" type="email"  name="useremail" value="{{ member.member_email }}">
                </p>
                <p> <label for="password">비밀번호:</label><br>
                    <input id="password" type="text" style="cursor: context-menu; color: red;" name="password" value="{{ member.member_password }}" readonly>
                </p>
                {% if member %}
                <input type="button" onclick="location.href='../login'" style="width: 105px;margin: 0px 2px;margin-left: -5px;" value="로그인 하러가기">
                {% else %}
                <input type ="submit" style="width: 80px;margin: 0px 2px;" value="찾기">
                {% endif %}
                <a href = "javascript:history.back();"><input type="button" style="width: 80px;margin: 0px 2px;" value="뒤로가기"></a>
            </form>
        </div>
    </body>
    <script>
        {% if msg %}
            alert('{{ msg }}');
        {% endif %}
    </script>
</html>

honssa/templates/user/login.html
{% load static %}
<!DOCTYPE html>

<html lang="ko">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Ecommerce">
    <link rel="stylesheet" href="{% static 'css/login.css' %}" type="text/css">
    <title>혼싸 로그인</title>
  </head>

  <body style="background-image: url({% static 'assets/img/honssamain.png' %});">
    <div class="login">
      <form action="" method="POST">
          {% csrf_token %}
        <p> <label for="username">아이디:</label><br>
            <input id = "username" type="text" name = "username">
        </p>
        <p> <label for="password">비밀번호:</label><br>
            <input id = "password" type="password"  name = "password">
        </p>
        <div class = "login_coordinate">
            <input type ="submit" value="로그인" class="login_coordinate">
        </div>
        </p>
    </form>
      <p>
          <a href ="{% url 'user:signup' %}"class="gmf" >회원가입</a>
          <a href ="{% url 'user:find_id' %}" class="gmf">아이디찾기</a>
          <a href ="{% url 'user:find_password' %}" class="gmf">비밀번호찾기</a>
      </p>
     Copyright© 2020 I'm here alone. I'll give you a discount. All Rights Reserved <a href="/admin/login/" class="admin">honssa</a>
    </div>
  </body>
</html>

honssa/templates/user/signup.html
{% load static %}

<html lang="ko">
    <head>
        <meta charset="UTF-8">
        <title>회원가입</title>
        <link rel="stylesheet" href="{% static 'css/login.css' %}" type="text/css">
    </head>
    <body class="login" style="background-image: url({% static 'assets/img/honssamain.png' %});">
        <div class="login">
            <form action ="#" method = "POST">
                {% csrf_token %}
                <p>
                    <label for="name">이름:</label><br>
                    <input id = "name" type="text" name = "username">
                </p>
                <p> <label for="email">이메일:</label><br>
                    <input id = "email" type="email"  name = "useremail">
                </p>
                <p> <label for="id">아이디:</label><br>
                    <input id = "id" type="text"  name = "user_id">
                </p>
                <p> <label for="password">비밀번호:</label><br>
                    <input id = "password" type="password"  name = "password">
                </p>
                <p> <label for="password2">비밀번호 확인:</label><br>
                    <input id = "password2" type="password"  name = "password2">
                </p>
                <p>
                    <label>휴대전화</label><br>
                    <input type="tel" name = hpon>
                </p>
                <input type ="submit" style="width: 80px;margin: 0px 2px;" value="가입하기" >
                <a href = "{% url 'user:logout' %}"><input type="button" style="width: 80px;margin: 0px 2px;" value="뒤로가기"></a>
            </form>
        </div>
    </body>
</html>