honssa/admin/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import *

app_name = "admin"

urlpatterns = [
    path('login/', admin_login, name = 'admin_login'),
    path('index/', admin_index, name = 'admin_main'),
    path('faq/', faq_manage, name = 'faq_manage'),
    path('order/', order_manage, name = 'order_manage'),
    path('order/detail/<int:id>', order_detail, name='order_detail'),
    path('logout/', admin_logout, name='admin_logout'),
    path('product/register/', product_register, name='product_register'),
    path('product/', product, name='product'),
    path('product/delete/<int:id>', product_delete, name='product_delete'),
    path('product/edit/<int:id>', product_edit, name='product_edit'),
    path('member/', member_manage, name='member'),
    path('update/<int:id>', member_update, name='info_update'),
    path('faq/', faq_manage, name='m2m_faq'),
    path('answer/<int:id>', answer_window, name='m2m_answer'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

honssa/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include('admin.urls')),
    path('user/', include('user.urls')),
    path('honssa/', include('honssauser.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

honssa/user/urls.py
from django.urls import path
from .views import *

app_name = "user"

urlpatterns = [
    path("login/",login_view, name="login"),
    path("logout/",logout_view , name="logout"),
    path("signup/",signup_view, name="signup"),
    path("find_id/",find_id, name="find_id"),
    path("find_password/",find_password, name="find_password")
]

honssa/templates/base2.html
{% load static %}
{% if user.is_authenticated %}

<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>{% block title%}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap-responsive.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/fullcalendar.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/maruti-style.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/honssa-deok.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/maruti-media.css' %}" class="skin-color"/>

    {% block script %}
    {% endblock %}

    {% block style %}
    {% endblock %}
</head>
<body>
<!--Header-part-->
<div id="header">
  <h1 background-color="black"></h1>
</div>
<!--close-Header-part-->

<!--top-Header-messaages-->
<!--<div class="btn-group rightzero"> <a class="top_message tip-left" title="Manage Files"><i class="icon-file"></i></a> <a class="top_message tip-bottom" title="Manage Users"><i class="icon-user"></i></a> <a class="top_message tip-bottom" title="Manage Comments"><i class="icon-comment"></i><span class="label label-important">5</span></a> <a class="top_message tip-bottom" title="Manage Orders"><i class="icon-shopping-cart"></i></a> </div>-->
<!--close-top-Header-messaages-->

<!--top-Header-menu-->
<div id="user-nav" class="navbar navbar-inverse">
  <ul class="nav">
    <li class=""><a title="" href="{% url 'admin:admin_logout' %}"><i class="icon icon-share-alt"></i> <span class="text">Logout</span></a></li>
    <li class=""><a title="" href="/honssa/main/"><i class="icon icon-home"></i> <span class="text">Home Page</span></a></li>
  </ul>
</div>
<!--close-top-Header-menu-->

<div id="sidebar"><a href="#" class="visible-phone"><i class="icon icon-home"></i> Dashboard</a>  <ul>
    <li class="active"><a href="/admin/index"><i class="icon icon-home"></i> <span>메인페이지</span></a> </li>
    <li calss="submenu"><a href="/admin/member/"><i class="icon icon-user"></i> <span>회원관리</span></a>
      <ul>
        <li><a href="/admin/member/">회원목록</a></li>
      </ul>
    </li>
    <li calss="submenu"><a href="/admin/product/"><i class="icon icon-shopping-cart"></i><span>상품관리</span></a>
      <ul>
        <li><a href="/admin/product/">상품목록</a></li>
        <li><a href="/admin/product/register/">상품등록</a></li>
      </ul>
    </li>
    <li calss="submenu"><a href="/admin/order/"><i class="icon icon-check"></i> <span>주문관리</span></a>
      <ul>
        <li><a href="/admin/order/">주문목록</a></li>
      </ul>
    </li>
    <li class="submenu"> <a href="/admin/faq"><i class="icon icon-th-list"></i> <span>문의관리</span</a>
      <ul>
        <li><a href="/admin/faq">1:1 문의관리</a></li>
      </ul>
    </li>
  </ul>
</div>
<div>
{% block content %}
{% endblock %}
</div>
</body>
<footer>
    <!--footer-part-->
    <div class="row-fluid">
      <div id="footer" class="span12"> 2020 &copy; Honssa Admin. Made by <a href="https://velog.io/@pds8462" style="color: #ddd;">bbyeong.log</a></div>
    </div>
</footer>
</html>
{% else %}
{% load static %}
<html lang="ko">

    <head>
        <title>혼싸 관리자페이지</title><meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
        <link rel="stylesheet" href="{% static 'css/bootstrap-responsive.min.css' %}" />
        <link rel="stylesheet" href="{% static 'css/maruti-login.css' %}" />
    </head>
    <body>
        <div id="loginbox">
            <form id="loginform" class="form-vertical" action="/admin/login/">
                <div class="control-group normal_text"> <h3><img src="{% static 'img/logo.png' %}" alt="Logo" /></h3></div>
                <div class="control-group" style="text-align: center">
                    <div style="font-size: 25px;margin: 0px auto;height: 100px;line-height: 100px;">로그인이 필요합니다.</div>
                <div class="form-actions">
                    <span class="pull-right"><input type="submit" class="btn btn-success" value="로그인 하러 가기"/></span>
                </div>
            </form>
        </div>

        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/maruti.login.js' %}"></script>
    </body>

</html>
{% endif %}